### ISSUE TITLE
python3-pathlib

### ISSUE THREAD

**Issue by claytondukes** [lephisto/tesla-apiscraper#58]
Your main readme has: 
```
apt install python3 python-pathlib python3-pip python3-influxdb
```
But I believe it should be `python-pathlib`

**Comment by ddaddy** [comment]
The readme says `python3-pathlib` which gives me the error `Unable to locate package python3-pathlib`
`python-pathlib` worked, Thanks

**Comment by stefan52a** [comment]
Thanks for all your work!. Working nicely here.

So many new things I learn from this nice software. Grafana, inlfux, reading the issues...

If you find time: Please change readme accordingly (python-pathlib instead of python3-pathlib). Or should I do this via a PR?

Also in the readme, several in
`apt install npm
cd /var/lib/grafana/plugins
git clone https://github.com/lephisto/grafana-trackmap-panel
cd grafana-trackmap-panel
git checkout v2.0.4-teslascraper
npm install
npm run build`

need sudo, right?

Also is the docker (docker-compose) not up to date (re: python3) yet? I get several invalid syntax on the print() function (probably python2 vs python3 issue?). Or is my setup wrong?
