### ISSUE TITLE
Question - How to update dashboard and save json?

### ISSUE THREAD

**Issue by bahree** [lephisto/tesla-apiscraper#67]
Sorry if this is obvious- I finally got to working this in a docker container, and when I update the layout of the dashboard (want to default to Miles and F) - and try and save it, I get the error cannot save provisioned dashboard. Where do I save the json file?

Also is the date on the host (raspberry pi) stored in /opt/apiscraper? If I want to migrate the container from one host to another and don't want to lose the existing data logged (or save it as a backup) - what files do I copy?

Thanks.

**Comment by lephisto** [comment]
You have to copy the mapped drives. Have you used the docker-compose setup? Then the Influx DB resised in /opt/apiscraper/influxdb and the grafana settings in /opt/apiscraper/grafana.

**Comment by lephisto** [comment]
Modifying Dasboards ist easy. Just copy the default ones (the are not changeable because they were provisioned).

**Comment by bahree** [comment]
Thanks @lephisto. On the dashboard, where do I save the updated json - once I modify the dashboard? I see in the "home" directory /provisioning/dasahboard (pasted below in my case) - would that be where I copy it, or does it need to be inside the container file system?
`pi@pi-server:~/tesla-apiscraper/provisioning/dashboards $`

Also this thing pinging every second to the Tesla API's seems a lot to me, if I want to delay that more - where do I configure it, or is that not possible right now?

Appreciate your help and patience! Thanks.

**Comment by lephisto** [comment]
@bahree it only pings in that frequency if the car is driving. that makes sense because you may want to have a fine granularity of the gps coordinates and speed. if the car is left alone, the polling throttles down.

regarding the dashboards: if you use the docker version, the preprovisioned dashboards can't be changed. expoert the json within grafana and reimport them with another id, and make the changes there.
